version: '2'

services:
  dev:
    image: rogerp/sdsfuse:0.1
    build:
      context: ./
      dockerfile: ./Dockerfile_local_dev
    volumes:
      - ../../:/usr/local/src/sdsfuse
    tty: true
    privileged: true
    stdin_open: true


  deploy:
    image: rogerp/sdsfuse:deploy
    build:
      context: ./
      dockerfile: ./Dockerfile
    privileged: true
    stdin_open: true
    tty: true
